eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
#      To prevent overriding the properties defined in the config file in the other projects
      override.system-properties: false