spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/products
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30  # Interval at which the client sends heartbeats
    leaseExpirationDurationInSeconds: 90  # How long the server waits after the last heartbeat before considering the instance down
    preferIpAddress: true  # Use IP address instead of hostname
server:
  port: 8050
